#You will need to work with two files for this exercise and solve the following tasks:
#Task One: Grab the Google Drive link from the .csv file. (Hint: Its along the diagonal).
#Task Two: Download the PDF from the Google Drive link 
#(we already downloaded it for you just in case you can't download from Google Drive) 
#and find the phone number that is in the document. 
#Note: There are different ways of formatting a phone number!
import csv
import PyPDF2
#Grab all the lines of data.

data = open('C:\\Users\\prinfnu\\Documents\\Python Scripts\\Exercise_Files\\find_the_link.csv',encoding="utf-8")
csv_data = csv.reader(data)
data_lines = list(csv_data)
#print(data_lines)
#the link will be generated by picking diagonal elements
# i.e. 1st element from ist row, 2nd element from 2nd row, 3rd element form 3rd row etc
link_list = []
for row_num,data in enumerate(data_lines):
    link_list.append(data[row_num])

drive_link=''.join(link_list)
print("link is: ",drive_link)

#get the phone number from pdf
f = open('C:\\Users\\prinfnu\\Documents\\Python Scripts\\Exercise_Files\\Find_the_Phone_Number.pdf','rb')
pdf = PyPDF2.PdfReader(f)
print("No of pages in PDF: ",len(pdf.pages))

#Find the phne no pattern
import re
pattern = r'\d{3}'
all_text = ''

for n in range(len(pdf.pages)):
    
    page = pdf.pages[n]
    page_text = page.extract_text()
    
    all_text = all_text+' '+page_text
for match in re.finditer(pattern,all_text):
    print(match)

#get the phone no
pattern = r'\d{3}.\d{3}.\d{4}' 
for n in range(len(pdf.pages)):
    
    page  = pdf.pages[n]
    page_text = page.extract_text()
    match = re.search(pattern,page_text)
    
    if match:
        print(match.group())


